### ISSUE TITLE
`propWithModel` and friends should not verify lengths

### ISSUE THREAD

**Issue by lmbollen** [clash-lang/clash-protocols#81]
From the documentation:
```hs
-- | Test a protocol against a pure model implementation. Circuit under test will
-- be arbitrarily stalled on the left hand and right hand side and tested for
-- a number of properties:
--
--   * Whether it does not produce too little data.
--   * Whether it does not produce /more/ data than expected.
--   * Whether it responds to backpressure correctly
--   * Whether it (eventually) drives a /nack/ while in reset.
--
-- Finally, the data will be tested against the property supplied in the last
-- argument.
--
```

The first two should not be checked or be made optional. Currently your model has to exactly mimic the implementation regarding the production of transactions. This can require larger than desired efforts for no gain.

For example.
An `Axi4 Stream` 1 to n resizing component could receive transactions such as the ones below:
```hs
[ Axi4StreamM2S
    { _tdata = 0 :> Nil
    , _tkeep = True :> Nil
    , _tstrb = True :> Nil
    , _tlast = False
    , _tid = 0
    , _tdest = 0
    , _tuser = ()
    }
, Axi4StreamM2S
    { _tdata = 0 :> Nil
    , _tkeep = True :> Nil
    , _tstrb = True :> Nil
    , _tlast = False
    , _tid = 0
    , _tdest = 0
    , _tuser = ()
    }
, Axi4StreamM2S
    { _tdata = 0 :> Nil
    , _tkeep = False :> Nil
    , _tstrb = False :> Nil
    , _tlast = True
    , _tid = 0
    , _tdest = 0
    , _tuser = ()
    }
]
```
If the implementation produces:
```hs
[ Axi4StreamM2S
    { _tdata = 0 :> 0 :> Nil
    , _tkeep = True :> True :>Nil
    , _tstrb = True :> True :> Nil
    , _tlast = False
    , _tid = 0
    , _tdest = 0
    , _tuser = ()
, Axi4StreamM2S
    { _tdata = 0 :> 0 :> Nil
    , _tkeep = False :> False :>Nil
    , _tstrb = False :> False :> Nil
    , _tlast = True
    , _tid = 0
    , _tdest = 0
    , _tuser = ()
    }
``` 
And the model produces:
```hs
[ Axi4StreamM2S
    { _tdata = 0 :> 0 :> Nil
    , _tkeep = True :> True :>Nil
    , _tstrb = True :> True :> Nil
    , _tlast = True
    , _tid = 0
    , _tdest = 0
    , _tuser = ()
```
I can still verify that it correctly communicated the packet, even though the model slightly deviates. However, `propWithModel` does not allow it, requiring me to mimic exactly the way my implementation merges transactions. Sometimes you just want to verify properties of the output without supplying model, making this restriction even more annoying.

In my opinion this should not be the default behavior because it makes it significantly harder to check simple properties.

**Comment by DigitalBrains1** [comment]
I'm not really sure how you'd solve your AXI thing with a model; they produce different values. I also thought that the model-based thing was too restrictive, and I initially solved it with a different function. In the end, it turned out that the counter-examples where unreadable and I just did away with the whole builtin `Hedgehog` support. Anyway... I have some opinions on this as well. The function I devised that unfortunately still gave an unreadable counterexample had this signature:


```haskell
testCircuit ::
  forall a b .
  (Test a, Test b, HasCallStack) =>
  -- | Options, see 'ExpectOptions'
  ExpectOptions ->
  -- | Test input
  ExpectType a ->
  -- | Expected test output
  ExpectType b ->
  -- | Implementation
  Circuit a b ->
  -- | Circuit output
  H.PropertyT IO (ExpectType b)

testCircuitSingleDomain ::
  forall dom a b .
  (Test a, Test b, C.KnownDomain dom, HasCallStack) =>
  -- | Options, see 'ExpectOptions'
  ExpectOptions ->
  -- | Test input
  ExpectType a ->
  -- | Expected test output
  ExpectType b ->
  -- | Implementation
  (C.Clock dom -> C.Reset dom -> C.Enable dom -> Circuit a b) ->
  -- | Circuit output
  H.PropertyT IO (ExpectType b)
```

and it was used approximately like this:

```haskell
prop :: H.Property
prop = H.property $ do
  [...]
  outStream <-
    testCircuitSingleDomain
      @C.System defExpectOptions inStream expectedStream
      (C.exposeClockResetEnable icmpEchoC)
  let outPkts = map streamToPacket $ chunkByPacket outStream
  H.footnote $ pPrintPacketsIEO (zip inPkts expectedPkts) outPkts ""
  H.assert (outPkts == expectedPkts)
```

I was hoping to get counterexamples from the `footnote` but instead they were formatted by the function I derived from `propWithModel`, because the lengths didn't match.

We can discuss this in the office perhaps.

**Comment by DigitalBrains1** [comment]
By the way, what I ended up doing: I tested functionality with a completely different `Hedgehog` test that used the formatting functions I provided to format counter-examples, so I could format them in a way a human can work with instead of raw `clash-protocols` samples.

And then I used `propWithModel` to test _only_ the stream invariants. My "model" was simply the component itself simulated without backpressure. So the data from the "model" was always equal to the data from the Device Under Test (DUT). It just verified the DUT correctly handled backpressure and stalls and such; actual functionality was verified in a different test.

**Comment by rowanG077** [comment]
It does produce semantically the same data which can you easily write a check for. The problem is that `propWithModel` enforces the same amount of output between model and SUT.

**Comment by rowanG077** [comment]
Assuming some `propWithModel` would just magically stop sampling at the correct time and some handwaving with functions that I didn't actually implement. 

```Haskell
-- Split stream into packets
chunkByPacket :: [AxiStreamM2S] -> [[AxiStreamM2S]]
...

-- Get all valid bytes
validBytes :: [AxiStreaM2S] -> [BitVector 8]
....

-- Check if two packets are semantically equivalent
equivalentPacket :: [AxiStreamM2S] -> [AxiStreamM2S] -> H.PropertyT IO ()
equivalentPacket pkt1 pkt2 = validBytes pkt1 === validBytes pkt2 -- Or add some more checks.

equivalentAxi :: [AxiStreamM2S] -> [AxiStreamM2S] -> H.PropertyT IO ()
equivalentAxi mOut cOut = sequence $ zipWith equivalentPacket (chunkByPacket mOut) (chunkByPacket cOut)
....

  propWithModel
    @C.System
    defExpectOptions
    genSomeInput
    model
    ckt
    equivalentAxi 
```

**Comment by DigitalBrains1** [comment]
Oh I'm so dumb, I forgot that you had this `ExpectType b -> ExpectType b -> PropertyT IO ()` argument! I thought it just always did `H.===`. Sorry!

**Comment by martijnbastiaan** [comment]
Given that the function is supplied the eq-function, yeah, the infra should probably not check for lengths.

> It seems like a superfluous specialisation of a more general Hedgehog function to me, so I'd like to know more about what the use is.

That's certainly true. It's mostly there because I could neatly write all the tests defined here using it: https://github.com/clash-lang/clash-protocols/blob/main/tests/Tests/Protocols/Df.hs.
